replicaCount: 1

clientName: null

image:
  repository: localhost:5000/helloworld
  pullPolicy: Always
  tag: 1.0.0

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: null
      paths:
        - path: /api/v1/hello
          pathType: ImplementationSpecific
  tls: []